spring.data.mongodb.uri=${MONGO_URI}
server.port=${PORT:8080}


spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a809cf001@smtp-brevo.com
spring.mail.password=RPY1HOgVDFKwsBbc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=aryankumar91237@gmail.com

clerk.issuer=https://funny-grub-61.clerk.accounts.dev
clerk.jwks-url=https://funny-grub-61.clerk.accounts.dev/.well-known/jwks.json